name: Publish to NPM & GitHub registry

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - registry: https://registry.npmjs.org/
            token_secret_key: NPM_TOKEN
          - registry: https://npm.pkg.github.com/
            token_secret_key: GITHUB_TOKEN
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version-file: .node-version
          check-latest: true
          cache: "pnpm"
          registry-url: ${{ matrix.registry }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Compile/Build TypeScript project if present
        run: pnpm run --if-present build 

      - name: Publish package to npm and GitHub packages registry
        run: pnpm run release --registry ${{ matrix.registry }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.token_secret_key] }}
